### ISSUE TITLE
'SparseTensor' object has no attribute 'coord_maps'

### ISSUE THREAD

**Issue by jmwang0117** [drprojects/DeepViewAgg#11]
Hello, thanks for your great work!

When I used **KITTI360** and the **pre-trained model** you provided to reproduce your paper, the following error occurred. How can I get the result? I installed the latest torchsparse using **pip**

Thanks a lot!

![d75bf929a431b7d0758c7c221260a1d](https://user-images.githubusercontent.com/51500826/187748120-15f1679b-47f6-4955-87b3-2ddcd8ac9d48.png)

**Comment by drprojects** [comment]
Hi @jmwang0117, sorry for the late reply, I was out-of-office for a while.

It indeed seems to be related to your `torchsparse` version. If you followed `install.sh`, you should have installed `torchsparse==1.1.0`. Please make sure you follow  `install.sh`, as some more recent library versions (eg `torchsparse` and `torch-geometric`) are not backward-compatible.

To install `torchsparse==1.1.0` you can use: 
```pip install --upgrade git+https://github.com/mit-han-lab/torchsparse.git@v1.1.0```

Please let me know if this solves your problem
