### ISSUE TITLE
TypeError: initialize() got an unexpected keyword argument 'config_path'

### ISSUE THREAD

**Issue by MuzammiFareed** [drprojects/DeepViewAgg#13]
with initialize(config_path=config_path):
    166             cfg = compose(config_name=config_name, overrides=overrides)
    167         OmegaConf.resolve(cfg)

TypeError: initialize() got an unexpected keyword argument 'config_path'

when i run the kitti inference notebook with pre train weights it show that to me . have any idea for it..

**Comment by drprojects** [comment]
Hi @MuzammiFareed 

It seems Hydra is unable to find the path to your config files. If you look at `torch_points3d/utils/config.py` in `hydra_read` which causes the error, you will see that Hydra looks for the configs in a relative path `config_path='../../conf'` by default. If you have changed the position/naming of the `conf/` or `notebooks` directory, it may have altered this mechanism. Try to investigate where `'../..'/conf` points in `hydra_read`. 

If this still does not work, please check your hydra version with ``pip list | grep hydra``. FYI thinks work fine for on my end with ``hydra-core=1.1.0``.
