### ISSUE TITLE
torch-points-kernels and  torchsparse install error with 3090, CUDA 11.2 

### ISSUE THREAD

**Issue by Daniellli** [drprojects/DeepViewAgg#20]
i use the install script  you privide to install, and some problem concerning to  torch-points-kernels and  torchsparse  show up.  i've try many way to solve it but still can not work. and error log is listed here : [error.log](https://github.com/drprojects/DeepViewAgg/files/10306040/error.log).

could you show me a way  to solve. 

appreciate for your help .

**Comment by drprojects** [comment]
Hello @Daniellli, 

Thanks for your interest in this project and sharing your feedback !

I have only tested this project on NVIDIA V100 GPUs  with CUDA 10.2, 11.2 and 11.4. Unfortunately, I do not have a 3090 at hand to reproduce your problem. 

Besides, as you have identified, the compilation errors you have seem to be library-specific. Have you tried referring to the libararies project pages and similar issues ? I had a quick look at their "issues" sections and saw multiple posts regarding installation/compilation issues.

- [torch-points-kernels](https://github.com/torch-points3d/torch-points-kernels)
- [torchsparse](https://github.com/mit-han-lab/torchsparse)

Besides `torch-points-kernels` and `torchsparse`, you seem to have troubles with `MinkowskiEngine` but, as stated in this [issue](https://github.com/drprojects/DeepViewAgg/issues/15), you can skip this install.

I am not sure how I can help you more, but here are some suggestions:

- look at the issues on the github repos of the troublesome dependencies (I saw plenty related to your problem)
- make sure your g++ / gcc versions match your CUDA version. In my case, I successfully installed the project with gcc 7.5 and gcc 8.3
- try with CUDA 10.2 or 11.4

**Comment by drprojects** [comment]
Hi, I am closing this issue for now.
