### ISSUE TITLE
Is it  possible to run with multiple GPU?

### ISSUE THREAD

**Issue by Daniellli** [drprojects/DeepViewAgg#21]
Hi,
Thank you for your kindly sharing codes.   As the title shown ,  I am wondering whether  such codebase supports multiple GPU run. 

appreciate for your  help.

**Comment by drprojects** [comment]
Hello @Daniellli, thanks for your interest in the project !

As of now, the code does not support multi-GPU. However, the current project is based on `torch-points3d`, which _does_ support multi-GPU. Only, I did not build DeepViewAgg to make use of it. So I think it may be doable but I do not have time to work on this at the moment and cannot vouch for it . 

If you decide to work on this, I would gladly accept a PR in this direction :wink:

**Comment by drprojects** [comment]
Closing this issue for now, feel free to open it again if need be
