### ISSUE TITLE
problem in creating no3d model

### ISSUE THREAD

**Issue by hahamidi** [drprojects/DeepViewAgg#26]
Hello 
when I change the model to "Res16UNet21-15_Res16Image21_late_max" I face this issue during the creation of the model:
##############################################################################

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-13-70fab76443ef> in <module>
----> 1 model: BaseModel = instantiate_model(copy.deepcopy(cfg), dataset)

~/notebook/DeepViewAgg/torch_points3d/models/model_factory.py in instantiate_model(config, dataset)
     42             % (model_module, class_name)
     43         )
---> 44     model = model_cls(model_config, "dummy", dataset, modellib)
     45     return model

~/notebook/DeepViewAgg/torch_points3d/models/segmentation/multimodal/sparseconv3d.py in __init__(self, option, model_type, dataset, modules)
     33         # No3D backbone init
     34         self.backbone_no3d = No3DEncoder(
---> 35             option.backbone_no3d, model_type, dataset, modules)
     36 
     37         # Set modalities based on the No3D backbone

~/notebook/DeepViewAgg/torch_points3d/applications/multimodal/no3d.py in __init__(self, model_config, model_type, dataset, modules, *args, **kwargs)
     22         # UnwrappedUnetBasedModel init
     23         super(No3DEncoder, self).__init__(
---> 24             model_config, model_type, dataset, modules)
     25 
     26         # Make sure the model is multimodal and has no 3D. Note that

~/notebook/DeepViewAgg/torch_points3d/models/base_architectures/backbone.py in __init__(self, opt, model_type, dataset, modules_lib)
     53         else:
     54             self._init_from_compact_format(
---> 55                 opt, model_type, dataset, modules_lib)
     56 
     57     def _init_from_compact_format(self, opt, model_type, dataset, modules_lib):

~/notebook/DeepViewAgg/torch_points3d/models/base_architectures/backbone.py in _init_from_compact_format(self, opt, model_type, dataset, modules_lib)
    151                     # length
    152                     assert idx < n_mm_blocks, \
--> 153                         f"Cannot build multimodal model: branching index " \
    154                         f"'{idx}' of modality '{m}' is too large for the " \
    155                         f"'{n_mm_blocks}' multimodal blocks."

AssertionError: Cannot build multimodal model: branching index '1' of modality 'image' is too large for the '1' multimodal blocks.
######################################################################

could you please let me what can I do?

**Comment by drprojects** [comment]
Hello @hahamidi, thanks for using this project !

Unfortunately, the model you are trying to use is no longer supported. I should have removed it from the config file. As a rule of thumb, the lower the models are in the config file, the more recent they are. If you are trying to do late fusion, I would recommend trying `ResUNet34-PointPyramid-late-Group` instead, or building your own model config from this one. 

Best, 

Damien
