### ISSUE TITLE
I found an issue while testing the project

### ISSUE THREAD

**Issue by chenyuhsiang** [drprojects/DeepViewAgg#29]
When I run this project, it appears that the test is combined with the train and validation processes. I want to inquire if there is a separate test in the code that allows me to use my own trained .pt file for testing independently.

**Comment by drprojects** [comment]
Can you please clarify which dataset you are using ? 

Also, what do you mean by

> my own trained .pt

Is that a model checkpoint or a preprocessed dataset ? 

Finally, and please correct me if I am wrong, are you asking if there is a way of running the inference of a model pretrained with the DeepViewAgg project on a dataset other than the currently-supported KITTI-360, S3DIS, or ScanNet ?

**Comment by drprojects** [comment]
Without further details from you, I am closing this issue.
