### ISSUE TITLE
Python 3.8.5

### ISSUE THREAD

**Issue by adikrishnanucd** [drprojects/DeepViewAgg#32]
@drprojects What changes would I need to make to the ***install.sh*** and/or the ***deep_view_aggregation.yml*** to set up the conda environment with _Python 3.8.5_ instead of _3.7.9_?

**Comment by drprojects** [comment]
Hi, you could try setting: 

```yaml
  - python=3.8.5 
```

in [here](https://github.com/drprojects/DeepViewAgg/blob/c94656c190b3a58c67587719091677907cd8db3f/deep_view_aggregation.yml#L76).

But, due to some dependencies limbo between Torch-Points3D, PyTorch Geometric, and Torch, I cannot vouch for the success of installing with such approach.

**Comment by adikrishnanucd** [comment]
I will try this. Thank you @drprojects.

**Comment by drprojects** [comment]
I would be curious to know if that works. Please keep let me know how that goes.

**Comment by adikrishnanucd** [comment]
There seemed to be a few errors when trying to run it with Python=3.8.5. Instead I am trying to run it with Python=3.7.9 as in the original .yml file. Is there anything I have to do to run the kitty-360 inference notebook through Jupyter notebook within VSCode. I have set the kernel to be the deep_view_aggregation conda environment. But for some reason it crashes when the second cell runs. I am getting this error @drprojects :

```
Disposing session as kernel process died ExitCode: undefined, Reason: ~/.local/lib/python3.8/site-packages/traitlets/traitlets.py:2395: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  FutureWarning,
~/.local/lib/python3.8/site-packages/traitlets/traitlets.py:2349: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'a8252496-ab37-400c-9a9f-b15955432e56' instead of 'b"a8252496-ab37-400c-9a9f-b15955432e56"'.
```

**Comment by drprojects** [comment]
This seems to be a VSCode-Jupyter issue: https://github.com/microsoft/vscode-jupyter/issues/9347

I can't help with that one, you will have to figure this out !

Best,

Damien

**Comment by adikrishnanucd** [comment]
@drprojects Would it be possible to run the kitti360_inference notebook as a Python script within the deep_view_aggregation conda environment? I am having trouble running it as a notebook, so I am thinking of copying the code over to a python script.

**Comment by drprojects** [comment]
Unless you are using VSCode to connect to a remote conda install, I am not sure as per why you are using VSCode to run a notebook. Can't you rather launch a `jupyter lab` or `jupyter notebook` from your bash and open the notebook in your browser ?

Of course, the notebook is just a tool for people to get started. You can definitely write your own scripts.  You can also get inspiration from the bash scripts in `scripts/`. 

But overall, the best way to get familiar with the project is to look into the code (which is abundantly commented) and read the paper :wink:

**Comment by adikrishnanucd** [comment]
@drprojects I am using VSCode to connect to a remote conda install which is also a remote server where the code lies in. I will continue to try to run Jupyter lab directly, as running the Jupyter notebook from within VSCode continues to give me an error. On a first try, I have been having the kernel crash and restart when I try to run the second cell of the kitti360_inference notebook through Jupyter lab. I am trying to figure out why this is the case.

Thank you.

**Comment by adikrishnanucd** [comment]
@drprojects I was able to import all the necessary modules in the kitti360_inference.ipynb file. However, when I am trying to run the last cell, I get the following error when it calls the hydra_read function:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-fc785dddeef7> in <module>
     19 
     20 # Parse the arguments with Hydra and OmegaConf
---> 21 cfg = hydra_read(overrides, config_name='eval.yaml')
     22 OmegaConf.set_struct(cfg, False)
     23 

~/Research/sem_seg/minkowski_kitti/DeepViewAgg/torch_points3d/utils/config.py in hydra_read(overrides, config_path, config_name)
    163     with warnings.catch_warnings():
    164         warnings.simplefilter("ignore")
--> 165         with initialize(config_path=config_path):
    166             cfg = compose(config_name=config_name, overrides=overrides)
    167         OmegaConf.resolve(cfg)

~/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/hydra/initialize.py in __init__(self, config_path, job_name, caller_stack_depth)
     87             calling_module=calling_module,
     88             config_path=config_path,
---> 89             job_name=job_name,
     90         )
     91 

~/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/hydra/_internal/hydra.py in create_main_hydra_file_or_module(cls, calling_file, calling_module, config_path, job_name)
     50         )
     51 
---> 52         return Hydra.create_main_hydra2(job_name, config_search_path)
     53 
     54     @classmethod

~/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/hydra/_internal/hydra.py in create_main_hydra2(cls, task_name, config_search_path)
     59     ) -> "Hydra":
     60         config_loader: ConfigLoader = ConfigLoaderImpl(
---> 61             config_search_path=config_search_path
     62         )
     63 

~/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py in __init__(self, config_search_path)
     53     ) -> None:
     54         self.config_search_path = config_search_path
---> 55         self.repository = ConfigRepository(config_search_path=config_search_path)
     56 
     57     @staticmethod

~/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/hydra/_internal/config_repository.py in __init__(self, config_search_path)
     63 
     64     def __init__(self, config_search_path: ConfigSearchPath) -> None:
---> 65         self.initialize_sources(config_search_path)
     66 
     67     def initialize_sources(self, config_search_path: ConfigSearchPath) -> None:

~/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/hydra/_internal/config_repository.py in initialize_sources(self, config_search_path)
     71             assert search_path.provider is not None
     72             scheme = self._get_scheme(search_path.path)
---> 73             source_type = SourcesRegistry.instance().resolve(scheme)
     74             source = source_type(search_path.provider, search_path.path)
     75             self.sources.append(source)

~/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/hydra/_internal/sources_registry.py in resolve(self, scheme)
     28             supported = ", ".join(sorted(self.types.keys()))
     29             raise ValueError(
---> 30                 f"No config source registered for schema {scheme}, supported types : [{supported}]"
     31             )
     32         return self.types[scheme]

ValueError: No config source registered for schema pkg, supported types : [file, structured]
```

Do you know how I can fix this error?

Thank you in advance, and sorry for the trouble.
