### ISSUE TITLE
Accuracy is low for Validation dataset

### ISSUE THREAD

**Issue by adikrishnanucd** [drprojects/DeepViewAgg#37]
Hello @drprojects,

I was wondering if there are any changes I need to make to run the kitti360_inference code with the CPU instead of the GPU.

Thank you,
Aditya

**Comment by drprojects** [comment]
Hi, we do not support CPU inference, because `torchsprase` does not. If you wanted to run on CPU, you would need to switch to `MinkowskiEngine` sparse convolution library, but I do not have time to provide support for this.
Best,
Damien
