### ISSUE TITLE
how to load and play with a small portion of the KITTI-360 dataset

### ISSUE THREAD

**Issue by Cemm23333** [drprojects/DeepViewAgg#9]
Hi @drprojects, thanks for your wonderful work.
Now I 'm running notebooks  kitti360_visualization.ipynb and want to load and play with a small portion of the KITTI-360 dataset.I make 'mini' set to True  but it doesn't work.After loading  a small portion of the KITTI-360 dataset,it starts to download all of  the KITTI-360 dataset.

**Comment by Cemm23333** [comment]
It is my mistake.I  only download the train and val set.

**Comment by drprojects** [comment]
Hello @Cemm23333, 
You are not entirely wrong, the "mini" option is intended to facilitate experimenting with KITI-360 by preprocessing and loading in memory only a small portion of the dataset. However, it will still download all 3D data and 2D data from the KITTI-360 server. For 3D data, there is not workaround, the KITTI-360 website does not let you choose which 3D acquisition sequence/window to download. However, if you want to save time/memory, you can tune `scripts/datasets/download_kitti360_2d_raw.sh` to only download sequences of interest (the 'mini' dataset only calls for sequences 0 and 8 for instance) for cameras of interest (camera 0 is all you need to reproduce the papers results). See http://www.cvlibs.net/datasets/kitti-360/download.php and http://www.cvlibs.net/datasets/kitti-360/documentation.php for more information on the dataset.
